### ISSUE TITLE
get_appsearch_document_id() should return the id field in the serializer

### ISSUE THREAD

**Issue by calitidexvii** [CorrosiveKid/django_elastic_appsearch#108]
The document ID is statically generated in [get_appsearch_document_id()](https://github.com/CorrosiveKid/django_elastic_appsearch/blob/b4fdca55b262b77b3b7fcbffb8f535bdcf774c92/django_elastic_appsearch/orm.py#L89). If you set a custom "id" field in your serializer, [delete_from_appsearch()](https://github.com/CorrosiveKid/django_elastic_appsearch/blob/b4fdca55b262b77b3b7fcbffb8f535bdcf774c92/django_elastic_appsearch/orm.py#L107) fails to delete the object because the generated ID isn't the same as the actual document ID. This is potentially confusing behavior and should be documented.

Is there a way to allow the serializer be the source of truth on the ID?

Here's a possible implementation:
```
    def get_appsearch_document_id(self):
        """Get the unique document ID."""
        _serialiser = self.serialise_for_appsearch()
        if _serialiser.get('id'):
            return _serialiser['id']
        else:
            return '{}_{}'.format(type(self).__name__, self.pk)
```

**Comment by CorrosiveKid** [comment]
If you need to set up a custom document id, you can simply override the `get_appsearch_document_id` method on your model class. This way, you don't have to change the id field on the serialser at all.

**Comment by CorrosiveKid** [comment]
However, I do agree that it would be nice to have some documentation around this specific use case, so I'll leave this issue open until that's done.
